spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_socials
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: twoichai
    password: twoichai
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
          # required: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000 # a day
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 8088